name: Build, Push Docker Image & Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kdradgzl/hello-go:latest

      - name: Decode and configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
        shell: bash

      - name: Install gke-gcloud-auth-plugin
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          curl -LO https://storage.googleapis.com/gke-gcloud-auth-plugin/release/latest/linux/amd64/gke-gcloud-auth-plugin
          chmod +x gke-gcloud-auth-plugin
          sudo mv gke-gcloud-auth-plugin /usr/local/bin/

      - name: Set KUBECONFIG and verify contexts
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config get-contexts

      - name: Deploy with Helm
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          helm upgrade --install hello-go-release ./hello-go --namespace default

