name: Build, Push Docker Image & Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kdradgzl/hello-go:latest

      - name: Authenticate to GCP and configure kubeconfig
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project aerobic-gantry-459812-k1
          gcloud container clusters get-credentials hello-go-cluster --zone us-central1-c --project aerobic-gantry-459812-k1
        shell: bash

      - name: Install kubectl, Helm and gke-gcloud-auth-plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https curl ca-certificates gnupg software-properties-common

          # Install kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

          # Install Helm
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

          # Install gke-gcloud-auth-plugin
          curl -LO https://storage.googleapis.com/gke-gcloud-auth-plugin/release/latest/linux/amd64/gke-gcloud-auth-plugin
          chmod +x gke-gcloud-auth-plugin
          sudo mv gke-gcloud-auth-plugin /usr/local/bin/
        shell: bash

      - name: Verify Kubernetes context
        run: |
          kubectl config get-contexts
          kubectl get nodes

      - name: Deploy with Helm
        run: |
          helm upgrade --install hello-go-release ./hello-go \
            --namespace default \
            --create-namespace \
            --set image.repository=kdradgzl/hello-go \
            --set image.tag=latest \
            --set replicaCount=1 \
            --set service.type=LoadBalancer


