name: Build, Push Docker Image & Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # GCP auth için gerekli

    steps:
      # 1. Kod Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Docker İşlemleri
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kdradgzl/hello-go:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 3. GCP ve Kubernetes Auth
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # JSON formatında olmalı!

      - name: Set up GCloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: aerobic-gantry-459812-k1

      - name: Install gke-gcloud-auth-plugin
        run: |
          ARCH=amd64
          OS=$(uname | tr '[:upper:]' '[:lower:]')
          curl -LO https://storage.googleapis.com/gke-gcloud-auth-plugin/release/latest/$OS/$ARCH/gke-gcloud-auth-plugin
          chmod +x gke-gcloud-auth-plugin
          sudo mv gke-gcloud-auth-plugin /usr/local/bin/

      - name: Configure Kubernetes
        run: |
          gcloud container clusters get-credentials hello-go-cluster \
            --zone us-central1-c \
            --project aerobic-gantry-459812-k1
          kubectl config get-contexts

      # 4. Helm Kurulum ve Deploy
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.14.4'

      - name: Deploy with Helm
        run: |
          helm upgrade --install hello-go-release ./hello-go \
            --namespace default \
            --create-namespace \
            --set image.repository=kdradgzl/hello-go \
            --set image.tag=latest \
            --atomic --wait --timeout 5m

